Skyscanner/eslint-config-skyscanner

changelog.md, index.js, package-lock.json, package.json, test/pass.jsx
Things to discuss:
- Should this be a major release as it's likely to contain 'breaking' changes, i.e. consumer builds probably won't pass due to all the rule changes.
- In our monorepo we've added a lot of rule opt-outs to `.eslintrc`. Should those be mirrored here? Or is it left up to consumers. Maybe we could put the opt-outs into the `.eslintrc` of `backpack-react-scripts`?
=> [BPK-964] Upgrade eslint versions

CHANGELOG.md, index.js, package.json
Upgraded the following peer dependencies:
- babel-eslint: ^8.2.5 -> ^8.2.6
- eslint: ^4.19.1 -> ^5.4.0
- eslint-config-airbnb: ^17.0.0 -> ^17.1.0
- eslint-plugin-import: ^2.13.0 -> ^2.14.0
- eslint-plugin-jsx-a11y: ^6.1.0 -> ^6.1.1
- eslint-plugin-react: ^7.10.0 -> ^7.11.1
- eslint-plugin-backpack: ^0.2.0 -> ^0.2.2
I've tested this on the backpack codebase and there are no issues, apart from:
- Modified from upstream eslint configuration to assert 'either' as opposed to 'both'. See https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js#L61.
=> [NOJIRA] Upgraded eslint-config-airbnb

CHANGELOG.md, package.json
Looking at the changelogs...
[babel-eslint](https://github.com/babel/babel-eslint/releases): 
- they now use babel 7 under the hood
[eslint](https://github.com/eslint/eslint/blob/master/CHANGELOG.md): 
- nothing major
=> [NOJIRA] Upgrade babel-eslint

index.js
Hi,
I think it makes sense to enforce some convention on the order of the imports and the new lines between them.
In my opinion, this helps a bit when reading the code, and also standardising a bit more the imports.
=> Add "import/order" rule

CHANGELOG.md, index.js, package.json
Integrate eslint-plugin-skyscanner-dates, setting the default to `warn`
=> DINGO-1191: Integrate eslint-plugin-skyscanner-dates

CHANGELOG.md, index.js, package.json
When disabling some eslint rule, it's very easy to make mistakes like not enabling it again, forgetting to remove the disabled rule when the code is refactored...
This plugin checks those cases, allowing a safer way of disabling eslint rules.
I think it would be very useful to include it in our configuration.
I've set all of them to just warn (they error by default), as given those are not fixed automatically with `--fix` it might be hard for some repos to fix them all manually (although personally I would trigger an error and release the new version as major, but maybe this can be changed in a future release, once this one already has a good adoption).
=> Integrate "eslint-plugin-eslint-comments" plugin

CHANGELOG.md, index.js, package.json
This plugin should save us from accidentally committing focused tests. 
The default configuration also spots other issues with jest tests, like exactly the same names of tests inside a describe block etc. 
The full list of defaults can be found [here](https://github.com/jest-community/eslint-plugin-jest/blob/master/src/index.ts)
=> Integrate "eslint-plugin-jest"

CHANGELOG.md, index.js, package-lock.json, package.json
I noticed the recently added `eslint-plugin-jest` has a section with related projects: https://github.com/jest-community/eslint-plugin-jest#related-projects
This section mentions `eslint-plugin-jest-formatting`: https://github.com/dangreenisrael/eslint-plugin-jest-formatting
This looks like something that aligns to Prettier, as it enforces adding new lines before/after `expect` (when set to `strict`), `beforeEach`/`it`/... (when set to `recommended`) making the code easier to read.
What do you think about adding this plugin?
=> Add "jest-formatting" plugin

.spelling, CHANGELOG.md, index.js, package-lock.json, package.json
React 16.3 introduced `UNSAFE_componentWillReceiveProps` as an alias for `componentWillReceiveProps`, as this will be removed in React 17 (see https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)
This PR changes the behaviour of `camelcase` to allow the prefix `UNSAFE_`.
=> Allow alias for deprecated React component lifecycle methods

CHANGELOG.md, index.js, package-lock.json, package.json
[`eslint-plugin-jest-dom`](https://github.com/testing-library/eslint-plugin-jest-dom) includes some lint rules to use with `jest-dom`.
=> Integrate "eslint-plugin-jest-dom"

CHANGELOG.md, README.md, docs/migration-from-5-to-6.md
`eslint-plugin-react` shows a warning when running eslint in a project without React:
`Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.`
Adding a version in `.eslintrc.json` silens it:
```
"settings": {
"react": {
"version": "16"
}
}
```
It's worth highlighting this in the migration guide and the readme.
=> Add React config info

CHANGELOG.md, package-lock.json, package.json
Upgrading to the new dependency `1.0.0` - nothing is breaking in that version except for dropping support for lower than v12 of Node, so no major impact to the project with rules
=> [NO JIRA]: Updating eslint-plugin-backpack dependency

.spelling, CHANGELOG.md, docs/migration-from-7-to-8.md, index.js, main.js, package-lock.json, package.json, test/pass.jsx
Update some major versions:
- Updated `eslint` to `7.2.0`
- Updated `eslint-plugin-jest` to `23.13.2`
- Updated `eslint-plugin-react-hooks` to `4.0.4`
- Updated `prettier` to `2.0.5`
Also some minor:
- Updated `eslint-config-airbnb` to `18.2.0`
- Updated `eslint-plugin-jsx-a11y` to `6.3.0`
=> [WIP] Update major versions of eslint and prettier

UNRELEASED.md, index.js
'Tools over rules'.
`[1, 2, 3]` can be typed in TypeScript as `number[]` or `Array<number>`.
`[1, 'two', 3]` can be typed as `Array<number | string>` or `(number | string)[]` 
A linting rule already exists for providing consistency: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/array-type.md
This PR choses `array-simple`.
> Use T[] or readonly T[] for simple types (i.e. types which are just primitive names or type references). Use Array<T> or ReadonlyArray<T> for all other types (union types, intersection types, object types, function types, etc).
`T[]` is preferred for simple types as it matches what the syntax used for `tsc` error messages. It is preferred to match `tsc` if there is no downside. It is felt that due to `tsc` always …
=> TypeScript array type linting

.husky/pre-commit, package.json
This PR upgrades lint-staged to the latest version and due to husky being on v7 upgraded it to use the correct format as husky was not actually runnng due to the new format from v6/v7
=> Upgrading lint-staged to latest

UNRELEASED.md, index.js
This would mean we bump a minor version.
Enforces our internal style guide of using `type` before a type import.
```js
// do
import type { MyType } from './types' 
// do not
import { MyType } from './types
```
https://stackoverflow.com/questions/61412000/do-i-need-to-use-the-import-type-feature-of-typescript-3-8-if-all-of-my-import
Released a beta under `eslint-config-skyscanner@10.4.0-beta.0` and tested it in one of our TypeScript projects.
=> NO-JIRA: Add consistent-type-imports - prefer type imports

.spelling, UNRELEASED.md, index.js, main.js, package-lock.json, package.json, test/pass.jsx
* Publish as scoped package (`@skyscanner/eslint-config-skyscanner`)
* Update import groups (and paths must be sorted alphabetically). The new order is:
1. builtin (node native)
1. react, react-dom, prop-types
1. external (other external libraries)
1. Backpack components
1. common package (shared functionailities between client and server)
1. parent (parent folders)
1. sibling (sibling folders)
1. index (same folder)
1. scss files
* Require object destructure key to be sorted
=> Update import order

index.js
Seems like `import/order` doesn't pick up `require('react-dom/server')` as `react-dom`, and places it somewhere bellow React imports.
**Before**: ([example](https://github.skyscannertools.net/adverts/content-lab/blob/master/app/routes/marketplace/viewContext.js#L8))
```js
const React = require('react');
const { getRumSetupHtml } = require('@skyscanner-internal/mshell-node-rum');
const {
template: { createClientSideParams },
} = require('node-microsite-core');
const ReactDOMServer = require('react-dom/server');
```
**After**:
```js
const React = require('react');
const ReactDOMServer = require('react-dom/server');
// rest of the imports
const { getRumSetupHtml } = require('@skyscanner-internal/mshell-node-rum');
const {
template: { createClientSideParams },
} = …
```
=> [NO-JIRA][import/order] Include react-dom/server to the list of top level imports

.spelling, UNRELEASED.md, index.js, test/pass.jsx
Take into account css files in import groups order (fixable using `--fix`). Treat the same as scss.
=> Take into account css files in import groups order

UNRELEASED.md, index.js
Alphabetisation seems to be creating issues in some projects, so removing this rule.
=> Remove alphabetise imports

UNRELEASED.md, index.js, test/pass.jsx
Backpack is moving from a package per component to a single package: `@skyscanner/backpack-web`
The `import/order` rule must be update to account for the new package.
=> Update "import/order" to take into account Backpack single package

package-lock.json, package.json
Uninstalling and stopping using `format-package` - in a recent PR #309 when checking the changes as it was a major bump, it appears that there is no active changelog after v5, therefore no way to securely check what is going on between versions.
For security and ensuring high safety standards we are removing this to ensure nothing untoward is going on!
=> [NO JIRA]: Uninstall format-package

README.md, UNRELEASED.md, eslintrc.template, main.js
When we moved to a scoped package we remembered to update the [warning message for people who already have an eslintrc](https://github.com/Skyscanner/eslint-config-skyscanner/blob/main/main.js#L93) but forgot to update so that the autogenerated eslintrc for people setting up from zero uses the correct extends config.
This PR updates the template.
=> NO-JIRA: Adjust eslintrc.template to reflect scoped package name

UNRELEASED.md, index.js
https://gojira.skyscanner.net/browse/SEARCHEXP-337
Eslint rules disallowed `import()` syntax for importing types to ensure consistency. However, in "ambient" module declarations (`.d.ts` files that extend a global module like a third-party library) are the only possibility to import them. Therefore, the rule has been updated in `eslint-config-rules` file allowing any`.d.ts` files to use `import()` syntax.
Before, the type import configurations had to be manually turned off for each file (see image below).
Before             |  After
:-------------------------:|:-------------------------:
=> [SEARCHEXP-337] Allow import() type imports in .d.ts files

.spelling, UNRELEASED.md, index.js, test/bpk-token-fail.jsx, test/package.json, test/pass.jsx, test/prettier-fail.jsx, test/react-fail.tsx
It is now discouraged to import react as follows:
```js
import React from 'react';
```
This is because the team have shown their intention to remove the default export in the future.
In preparation for this the react team encourage the following (Dan Abramov from the react team):
https://twitter.com/dan_abramov/status/1308739731551858689
There is also a codemod created by the react team to do this:
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports
This change standardises on the first syntax above (this may need discussion about whether it is the prefferd style), and makes it such that the user will see an error if using a different style:
=> Disable default import of react

.eslintrc.json, UNRELEASED.md, index.js, package-lock.json, package.json, test/pass.jsx
`babel-eslint` was deprecated on July 31, 2020 in favour of the package from Babel's main mono repo; ` @babel/eslint-parser`: https://github.com/babel/babel-eslint/pull/842/files.
This pull request moves `eslint-config-skyscanner` over in the least disruptive way to consumers. For those on standard supported Skyscanner tooling this should be a patch level change, but as we cannot say that is the case for everyone it should be released as a new major.
It has been released as a beta of `@skyscanner/eslint-config-skyscanner@13.3.0-beta.0` and tested locally in a mixture of JS, TS, JS&TS, and Node repositories with no unexpected errors.
It is a prerequisite to being able to support ESLint 8, released 1 year and 9 months ago.
The PR contains detailed release notes.
The local testing verifies …
=> [KOA-6213] Update from babel-eslint to @babel/eslint-parser

CHANGELOG.md, UNRELEASED.md, docs/releasing.md, package-lock.json, package.json
Brings in https://github.com/Skyscanner/eslint-plugin-backpack/blob/main/CHANGELOG.md#500, for missed ESLint 8 compatibility.
This will be a minor release.
=> [KOA-6221] Update eslint-plugin-backpack to v5 which supports ESLint 8

index.js, test/order-fail.jsx, test/package.json, test/pass.jsx
There is an issue from the mini-css-extract-plugin where when import order is mixed about, and causes CSS issues, so this PR looks to enforce a consistant import structure across all components to avoid the issue.
<details>
<summary>Example error</summary>
```
Failed to compile.
(undefined) chunk 1 [mini-css-extract-plugin]
Conflicting order. Following module has been added:
* css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/@skyscanner/backpack-web/bpk-component-button/src/BpkButtonV2/BpkButton.module.css
despite it was not able to fulfill desired ordering with these modules:
* css ./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/@skyscanner/backpack-web/bp …
```
=> [ARGG-741]: Add rule to set alphabetical order of imports

README.md, eslint-plugin-skyscanner-no-axios/package.json, eslint-plugin-skyscanner-no-axios/src/index.js, eslint-plugin-skyscanner-no-axios/src/rules/no-axios.js, eslint-plugin-skyscanner-no-axios/src/rules/no-axios.test.js, index.js, package-lock.json, package.json, test/no-axios-fail.jsx, test/package.json
What:
Adds a rule forbidding the use of axios library. The rule name is `skyscanner-no-axios/no-axios`
Why:
Axios is known to leak sensitive details in it's error objects
How:
- Created a minimal eslint plugin package in a subfolder of the repo
- Added a local install of that to the main package.json
- Added the necessary config/
=> [ARGG-857] Add rule forbidding the use of axios library

eslint-plugin-skyscanner-no-axios/src/rules/no-axios.js, eslint-plugin-skyscanner-no-axios/src/rules/no-axios.test.js
What:
Test if dynamic import argument is a string before testing if it's axios
Why:
It was breaking cases where the argument was an expression evaluating to string.
=> Test if dynamic import argument is a string

eslint-plugin-skyscanner-no-axios/package.json, eslint-plugin-skyscanner-no-axios/src/rules/no-axios.test.js
What:
Removes eslint from no-axios rule's peer dependencies
Why:
It's not really necessary as the parent package depends on eslint anyway, and might be causing issues with dependabot.
=> Remove no-axios rule peer dependency on eslint

.github/dependabot.yml
Patch versions generate a lot of toil without providing a high amount of value.
We can opt out of receiving automated PRs for these, while still receiving PRs for minor and major versions.
https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
=> Ignore patch version updates in dependabot config

package-lock.json, package.json
Bump @skyscanner/eslint-plugin-rules to allow access to the rule: `@skyscanner/rules/forbid-component-props`.
=> [LOOM-1339]: bump @skyscanner/eslint-plugin-rules

package-lock.json, package.json
Bump eslint-plugin-rules to v1.2.0
https://github.com/Skyscanner/eslint-plugin-rules/releases/tag/1.2.0
=> Bump eslint-plugin-rules to v1.2.0

index.js, package-lock.json, package.json
🎫 https://skyscanner.atlassian.net/browse/ST-6572
While migrating to Vitest ESLint was unable to resolve certain valid imports, specifically subpaths imports like [vitest/config](https://github.skyscannertools.net/skyscanner/banana/pull/15943/files/4f90265751b4dc1a2af449ec0b91051df51b78a1#diff-df3a80051c06b9cf40b0790523519e50deb7017be803c2b5d0b629fc56da07e1R1)
It seems that ESLint doesn’t know how to interpret [Vitest subpath](https://github.com/vitest-dev/vitest/blob/464218f42cb4812f4dba77674f2152606c4c215f/packages/vitest/package.json#L84) exports.
Change:
- Update ESLint settings to include a TypeScript and Node import/resolver
- Add eslint-import-resolver-typescript
This change should fix unresolved import errors for vitest/config and other valid TS/Node imports.
=> ST-6572 : Enable ESLint to resolve TypeScript and Node imports

index.js, package-lock.json, package.json
In eslint-config-skyscanner we use [eslint-plugin-typescript-enum](https://github.com/shian15810/eslint-plugin-typescript-enum) to ban use of TypeScript enums.
Unfortunately that package now appears unmaintained. A PR raised in September 2023 to refresh its dependencies took over a year to be acknowledged and is still pending final review.
In https://github.com/Skyscanner/eslint-plugin-rules/pull/45 we created an equivalent rule in Skyscanner's rule definitions.
The functionality of the rule remains exactly the same.
This PR swaps one for the other.
If someone was previously suppressing using comments like
```
// eslint-disable-next-line typescript-enum/no-enum
```
they will now need to use
```
// eslint-disable-next-line @skyscanner/rules/no-enum
```
=> Switch to using no-enum rule from @skyscanner/eslint-plugin-rules
